#!/bin/bash
# Modificado para não duplicar LOGS
pkill php
pkill mplayer
ps=`ps ax | grep /var/www/log.sh | grep -v grep | cut -d " " -f1`
ps2=`ps ax | grep /var/www/log_evento.sh | grep -v grep | cut -d " " -f1`
kill -9 $ps
kill -9 $ps2
> /var/www/nohup.out
echo 'delete from arquivos; delete from esquemas; delete from generos; delete from grades; delete from playlists; delete from programacoes;' | mysql radio
(cd /var/www/; nohup ./update.php; nohup ./musical.php ; sleep 5; nohup ./player.php &)
sleep 10
(cd /tmp; rm -f *)
(cd /var/log;  find .  *.gz -exec rm -f {} \;)
rm -f /var/www/nohup.out
